version: '3'
services:
  single-spa:
    build: ../sample-single-spa
    image: single-spa
    ports:
      - "5001:5000"
  sample-app:
    build: ../sample-app
    image: sample-app
    ports:
      - "5000:8082"
  sample-api:
    build: ../sample-api
    image: sample-api
    environment:
      - DB=mongodb://mongo:27017
      - DB_name=test
      - NODE_ENV=production
    ports: 
      - "8080:3000"
  mongo:
    image: mongo
    ports:
    - "27017:27017"